# .travis.yml
#
# This source file is part of the SDGInterface open source project.
# https://sdggiesbrecht.github.io/SDGInterface
#
# Copyright ©2018–2019 Jeremy David Giesbrecht and the SDGInterface project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

language: generic
matrix:
  include:
    - name: "macOS"
      os: osx
      osx_image: xcode10.2
      script:
        - "git config --global protocol.version 1"
        - "bash \"./Refresh (macOS).command\""
        - "bash \"./Validate (macOS).command\" •job macos"
    - name: "Linux"
      os: linux
      dist: xenial
      script:
        - "export SWIFT_VERSION=5.0"
        - "eval \"$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)\""
        - "bash \"./Refresh (macOS).command\""
        - "bash \"./Validate (macOS).command\" •job linux"
    - name: "iOS"
      os: osx
      osx_image: xcode10.2
      language: objective-c
      xcode_sdk: iphonesimulator
      script:
        - "git config --global protocol.version 1"
        - "bash \"./Refresh (macOS).command\""
        - "bash \"./Validate (macOS).command\" •job ios"
    - name: "watchOS"
      os: osx
      osx_image: xcode10.2
      script:
        - "git config --global protocol.version 1"
        - "bash \"./Refresh (macOS).command\""
        - "bash \"./Validate (macOS).command\" •job watchos"
    - name: "tvOS"
      os: osx
      osx_image: xcode10.2
      language: objective-c
      xcode_sdk: appletvsimulator
      script:
        - "git config --global protocol.version 1"
        - "bash \"./Refresh (macOS).command\""
        - "bash \"./Validate (macOS).command\" •job tvos"
    - name: "Miscellaneous"
      os: linux
      dist: xenial
      script:
        - "export SWIFT_VERSION=5.0"
        - "eval \"$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)\""
        - "bash \"./Refresh (macOS).command\""
        - "bash \"./Validate (macOS).command\" •job miscellaneous"
    - name: "Deployment"
      os: linux
      env:
        - secure: "O5o7Iu10Pk7hfyfcRBxcEw8G52INRoGCgLTDBladFxOZLx6a6yKaYu1RuYeOi2A2Y4SdGCI88Wk64rMVNh3t8j7chJUImGWTCt0Da8wOfVIub958MyXojU8ed2tKURkyfTrGm/fUc3ED0E/VGongGF8bYUOreVXFK6qJ8S2XtQROpgYA7mek25YMu9uvem8O3JvN6U+esbLmMx9n/GOkaPNcu1IOsRytbwzLdClWbkwhW8tgAF7ca9BEholyzw3LT2/9uigZaScjtifsKs+9xB6L4+3DLD9WL8+0A1YqQi1SmH1EpB7tigDe0DgEsI3ElRyJbBVfDIFRFbcmLihSc/mttBVbLVlcHD7b3jJ75jOpfBgBTH7UoYM2JHn6KzqrDp0SZXETUs6m76E5D0i6BtvqFIDU61WqIF1fKy/06/nMnt5vACeUZ9oVUfpB0QUjO78Xjziv/qsgEvoVlWgW8hjuB70MusJvNtGbWCY8cJjcx2LPqK7dEkEsx4xMc20W/SmZP8aQeGgZijuTD/kFJTryX27B1CGnRcOscSsIWiN3LiHZoV7zcM2czQxNSq3s6uIz+craAnz7H5+Ngrh5q39XSvlznlHUWhT7Is4H0sJvXAOSWYQmcbsB7ajQg5tJ5TDA5XS6GK4vyeueNXDpyWZVTVlHdzkkqbDFQP9InHs="
      if: branch = master and (not type = pull_request)

      deploy:
        provider: pages
        local_dir: docs
        github_token: $GITHUB_TOKEN
        skip_cleanup: true
      dist: xenial
      script:
        - "export SWIFT_VERSION=5.0"
        - "eval \"$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)\""
        - "bash \"./Refresh (macOS).command\""
        - "bash \"./Validate (macOS).command\" •job deployment"

cache:
  directories:
  - $HOME/Library/Caches/ca.solideogloria.Workspace
  - $HOME/.cache/ca.solideogloria.Workspace
