#if !canImport(ObjectiveC)
import XCTest

extension APITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APITests = [
        ("testArrayController", testArrayController),
        ("testAttributedString", testAttributedString),
        ("testButton", testButton),
        ("testButtonSet", testButtonSet),
        ("testCharacterInformation", testCharacterInformation),
        ("testCheckBox", testCheckBox),
        ("testCheckBoxCell", testCheckBoxCell),
        ("testDelegationInterceptor", testDelegationInterceptor),
        ("testDemonstrations", testDemonstrations),
        ("testFetchResult", testFetchResult),
        ("testFont", testFont),
        ("testImageView", testImageView),
        ("testKey", testKey),
        ("testKeyModifiers", testKeyModifiers),
        ("testLabel", testLabel),
        ("testLayoutConstraint", testLayoutConstraint),
        ("testLetterbox", testLetterbox),
        ("testNotification", testNotification),
        ("testPopOver", testPopOver),
        ("testPreferences", testPreferences),
        ("testRichText", testRichText),
        ("testSystemMediator", testSystemMediator),
        ("testTable", testTable),
        ("testTextEditor", testTextEditor),
        ("testTextField", testTextField),
        ("testView", testView),
    ]
}

extension InternalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InternalTests = [
        ("testApplicationName", testApplicationName),
        ("testNSApplicationDelegate", testNSApplicationDelegate),
        ("testUIApplicationDelegate", testUIApplicationDelegate),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(APITests.__allTests__APITests),
        testCase(InternalTests.__allTests__InternalTests),
    ]
}
#endif
