#if !canImport(ObjectiveC)
import XCTest

extension APITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APITests = [
        ("testAttributedString", testAttributedString),
        ("testCharacterInformation", testCharacterInformation),
        ("testFont", testFont),
        ("testLabel", testLabel),
        ("testRichText", testRichText),
        ("testTextEditor", testTextEditor),
        ("testTextField", testTextField),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(APITests.__allTests__APITests),
    ]
}
#endif
