#if !canImport(ObjectiveC)
import XCTest

extension APITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APITests = [
        ("testLetterbox", testLetterbox),
        ("testRowView", testRowView),
        ("testSwiftUIView", testSwiftUIView),
        ("testView", testView),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(APITests.__allTests__APITests),
    ]
}
#endif
