# Swift 5.7 (Ubuntu).yaml
#
# This source file is part of the SDGInterface open source project.
# https://sdggiesbrecht.github.io/SDGInterface
#
# Copyright ©2021–2023 Jeremy David Giesbrecht and the SDGInterface project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

name: Swift 5.7 (Ubuntu)

on: [push, pull_request]

jobs:
  Swift_5_7_Ubuntu:
    name: Swift 5.7 (Ubuntu)
    runs-on: ubuntu-20.04
    container: swift:5.7.3-focal
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Validate
      shell: bash
      run: |
        set -x
        swift test
